package org.flowlang.generators.manifest

class JenkinsManifestRenderer {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "jenkins")
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("// Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("// Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        sb.appendLine("// Projection model: notes-driven materialization; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note -> sb.appendLine("// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        sb.appendLine("pipeline {")
        sb.appendLine("  agent any")
        sb.appendLine("  options { timestamps() }")
        renderJenkinsParameters(manifest, sb)
        renderJenkinsTriggers(manifest, sb)
        renderJenkinsOpaqueEnvironment(manifest, sb)
        sb.appendLine("  stages {")
        manifest.jobs.forEach { job -> renderJenkinsJob(job, manifest, sb) }
        sb.appendLine("  }")
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderJenkinsParameters(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("  parameters {")
        manifest.inputs.forEach { input ->
            when (input.type) {
                "boolean" -> sb.appendLine("    booleanParam(name: '${groovyEscape(input.name)}', defaultValue: ${input.defaultValue?.toBooleanStrictOrNull() ?: false})")
                "option" -> sb.appendLine("    choice(name: '${groovyEscape(input.name)}', choices: [${input.choices.joinToString(", ") { groovyString(it) }}])")
                else -> sb.appendLine("    string(name: '${groovyEscape(input.name)}', defaultValue: ${groovyString(input.defaultValue ?: "")})")
            }
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsTriggers(manifest: TargetManifest, sb: StringBuilder) {
        val schedules = manifest.triggers.filter { it.type == "SCHEDULE" }
        if (schedules.isEmpty()) return
        sb.appendLine("  triggers {")
        schedules.forEach { trigger ->
            require(trigger.scheduleKind == "CRON") { "Executable Jenkins schedule '${trigger.id}' must be CRON." }
            val expression = requireNotNull(trigger.scheduleExpression) { "Jenkins schedule '${trigger.id}' is missing expression." }
            sb.appendLine("    cron(${groovyString(expression)})")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsOpaqueEnvironment(manifest: TargetManifest, sb: StringBuilder) {
        val opaqueNames = TargetProjectionDiagnostics.opaqueNames(manifest)
        if (opaqueNames.isEmpty()) return
        sb.appendLine("  environment {")
        opaqueNames.forEach { name ->
            sb.appendLine("    ${safeEnvName(name)} = credentials('${groovyEscape(name)}')")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        sb.appendLine("    stage(${groovyString(job.name)}) {")
        sb.appendLine("      steps {")
        sb.appendLine("        script {")
        if (job.steps.isEmpty()) {
            sb.appendLine("          error(${groovyString("Flow job '${job.id}' has no materialized target steps.")})")
        } else {
            job.steps.forEach { renderJenkinsStep(it, manifest, sb, "          ") }
        }
        sb.appendLine("        }")
        sb.appendLine("      }")
        sb.appendLine("    }")
    }

    private fun renderJenkinsStep(step: TargetStep, manifest: TargetManifest, sb: StringBuilder, indent: String) {
        step.mappingNotes.forEach { note -> sb.appendLine("${indent}// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        TargetProjectionDiagnostics.append(ProjectionTarget.JENKINS, step, manifest.inputs, sb, indent, "//")
        when (step.type) {
            "try" -> renderJenkinsTry(step, manifest, sb, indent)
            "try-body", "error-handler", "parallel", "parallel-branch", "loop", "match", "retry" ->
                step.children.forEach { renderJenkinsStep(it, manifest, sb, indent) }
            "condition" -> renderJenkinsCondition(step, manifest, sb, indent)
            "approval" -> sb.appendLine("${indent}input message: ${groovyString(step.params["message"] ?: "Approval required")}")
            else -> renderJenkinsLeaf(step, sb, indent)
        }
    }

    private fun renderJenkinsTry(step: TargetStep, manifest: TargetManifest, sb: StringBuilder, indent: String) {
        val body = step.children.firstOrNull { it.type == "try-body" }
        val handler = step.children.firstOrNull { it.type == "error-handler" }
        sb.appendLine("${indent}try {")
        body?.children.orEmpty().forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}} catch (flowError) {")
        handler?.children.orEmpty().forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}}")
    }

    private fun renderJenkinsCondition(step: TargetStep, manifest: TargetManifest, sb: StringBuilder, indent: String) {
        val condition = step.params["condition"] ?: "false"
        val rendered = TargetExpressionTranslator.groovy(
            condition,
            manifest.inputs,
            manifest.compatibility.expressionSupport
        )
        sb.appendLine("${indent}if ($rendered) {")
        step.children.forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}}")
    }

    private fun renderJenkinsLeaf(step: TargetStep, sb: StringBuilder, indent: String) {
        val opaqueNames = TargetProjectionDiagnostics.opaqueNames(step)
        if (opaqueNames.isNotEmpty()) {
            val items = opaqueNames.joinToString(", ") { TargetProjectionValue.mappingSpec(ProjectionTarget.JENKINS, it) }
            sb.appendLine("${indent}${TargetProjectionValue.boundary(ProjectionTarget.JENKINS)}([$items]) {")
            renderJenkinsLeafBody(step, sb, "$indent  ")
            sb.appendLine("${indent}}")
        } else {
            renderJenkinsLeafBody(step, sb, indent)
        }
    }

    private fun renderJenkinsLeafBody(step: TargetStep, sb: StringBuilder, indent: String) {
        val payload = requireNotNull(step.rendererPayload) { "Executable Jenkins step '${step.id}' has no renderer payload." }
        require(payload.kind == BuiltInProjectionPayloadKinds.JENKINS_STEP) {
            "Jenkins cannot render payload kind '${payload.kind}' for step '${step.id}'."
        }
        when (payload.reference) {
            "git" -> {
                val url = payload.parameters["url"].orEmpty()
                require(url.isNotBlank()) { "Jenkins git payload for '${step.id}' requires url." }
                val branch = payload.parameters["branch"].orEmpty().ifBlank { "main" }
                sb.appendLine("${indent}git branch: ${groovyString(branch)}, url: ${groovyString(url)}")
            }
            else -> error("Unsupported Jenkins structured payload reference '${payload.reference}' for step '${step.id}'.")
        }
    }
}

class GitHubActionsManifestRenderer(
    private val environmentEvidenceResolver: TargetEnvironmentSafetyEvidenceResolver = TargetEnvironmentSafetyEvidenceResolver()
) {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "github-actions")
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        sb.appendLine("# Projection model: notes-driven materialization; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note -> sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        sb.appendLine("name: ${yamlScalar(manifest.flowName)}")
        sb.appendLine("on:")
        val manual = manifest.triggers.isEmpty() || manifest.triggers.any { it.type == "MANUAL" }
        if (manual) {
            sb.appendLine("  workflow_dispatch:")
            renderGithubInputs(manifest, sb)
        }
        val schedules = manifest.triggers.filter { it.type == "SCHEDULE" }
        if (schedules.isNotEmpty()) {
            sb.appendLine("  schedule:")
            schedules.forEach { trigger ->
                require(trigger.scheduleKind == "CRON") { "Executable GitHub schedule '${trigger.id}' must be CRON." }
                val expression = requireNotNull(trigger.scheduleExpression) { "GitHub schedule '${trigger.id}' is missing expression." }
                sb.appendLine("    - cron: ${yamlScalar(expression)}")
            }
        }
        sb.appendLine("jobs:")
        manifest.jobs.forEach { job -> renderGitHubJob(job, manifest, sb) }
        return sb.toString()
    }

    private fun renderGithubInputs(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("    inputs:")
        manifest.inputs.forEach { input ->
            sb.appendLine("      ${sanitizeId(input.name)}:")
            sb.appendLine("        description: ${yamlScalar(input.name)}")
            sb.appendLine("        required: ${input.required}")
            val type = when (input.type) { "boolean" -> "boolean"; "option" -> "choice"; else -> "string" }
            sb.appendLine("        type: $type")
            if (input.choices.isNotEmpty()) {
                sb.appendLine("        options:")
                input.choices.forEach { sb.appendLine("          - ${yamlScalar(it)}") }
            }
            input.defaultValue?.let { sb.appendLine("        default: ${yamlScalar(it)}") }
        }
    }

    private fun renderGitHubJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val materializedSteps = job.steps.flatMap { it.flatten() }
        val opaqueNames = materializedSteps.flatMap { TargetProjectionDiagnostics.opaqueNames(it) }.distinct()
        sb.appendLine("  ${sanitizeId(job.id)}:")
        sb.appendLine("    name: ${yamlScalar(job.name)}")
        sb.appendLine("    runs-on: ubuntu-latest")
        if (job.dependsOn.isNotEmpty()) sb.appendLine("    needs: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        githubJobIf(job, manifest)?.let { sb.appendLine("    if: ${githubExpression(it)}") }
        if (job.metadata["approval"] == "true") {
            val environmentEvidence = environmentEvidenceResolver.resolve(manifest, job)
            sb.appendLine("    # Flow environment sensitivity: ${environmentEvidence.sensitivity}")
            sb.appendLine("    # Flow environment policy: ${environmentEvidence.policyPackageId}@${environmentEvidence.policyPackageVersion}")
            if (environmentEvidence.parameterEvidence.isNotEmpty()) {
                sb.appendLine("    # Flow environment evidence: ${environmentEvidence.parameterEvidence.sorted().joinToString(", ")}")
            }
            sb.appendLine("    # Flow environment decision: ${environmentEvidence.reason}")
            environmentEvidence.approvalEnvironment?.let { environment ->
                sb.appendLine("    environment: ${yamlScalar(environment)}")
            }
        }
        if (opaqueNames.isNotEmpty()) {
            sb.appendLine("    env:")
            opaqueNames.forEach { name -> sb.appendLine("      ${safeEnvName(name)}: ${TargetProjectionValue.bindingValue(ProjectionTarget.GITHUB_ACTIONS, name)}") }
        }
        require(materializedSteps.isNotEmpty()) { "Executable GitHub Actions job '${job.id}' has no steps." }
        sb.appendLine("    steps:")
        materializedSteps.forEach { step ->
            val payload = requireNotNull(step.rendererPayload) { "Executable GitHub Actions step '${step.id}' has no renderer payload." }
            require(payload.kind == BuiltInProjectionPayloadKinds.GITHUB_ACTION) {
                "GitHub Actions cannot render payload kind '${payload.kind}' for step '${step.id}'."
            }
            sb.appendLine("      - name: ${yamlScalar(step.name)}")
            sb.appendLine("        uses: ${yamlScalar(payload.reference)}")
            if (payload.parameters.isNotEmpty()) {
                sb.appendLine("        with:")
                payload.parameters.forEach { (name, value) -> sb.appendLine("          ${sanitizeId(name)}: ${yamlScalar(value)}") }
            }
        }
    }

    private fun githubJobIf(job: TargetJob, manifest: TargetManifest): String? {
        val own = job.metadata["condition"]?.let { TargetExpressionTranslator.github(it, manifest.inputs, manifest.compatibility.expressionSupport) }
        if (job.metadata["errorHandler"] == "true") {
            val parts = mutableListOf("always()", "failure()")
            if (!own.isNullOrBlank()) parts += "($own)"
            return parts.joinToString(" && ")
        }
        val needs = job.dependsOn.map { dep ->
            val safeDep = sanitizeId(dep)
            val isApproval = manifest.jobs.firstOrNull { sanitizeId(it.id) == safeDep }?.metadata?.get("approval") == "true"
            if (isApproval) "(needs.$safeDep.result == 'success' || needs.$safeDep.result == 'skipped')"
            else "needs.$safeDep.result == 'success'"
        }
        val parts = mutableListOf<String>()
        if (job.dependsOn.isNotEmpty()) parts += "always()"
        if (!own.isNullOrBlank()) parts += "($own)"
        parts += needs
        return parts.takeIf { it.isNotEmpty() }?.joinToString(" && ")
    }
}

class TektonManifestRenderer {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "tekton")
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Projection model: notes-driven materialization; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note -> sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        sb.appendLine("apiVersion: tekton.dev/v1")
        sb.appendLine("kind: Pipeline")
        sb.appendLine("metadata:")
        sb.appendLine("  name: ${sanitizeId(manifest.flowName)}")
        sb.appendLine("spec:")
        if (manifest.inputs.isNotEmpty()) {
            sb.appendLine("  params:")
            manifest.inputs.forEach { sb.appendLine("    - name: ${sanitizeId(it.name)}\n      type: string") }
        }
        sb.appendLine("  tasks:")
        manifest.jobs.forEach { job -> renderTektonTask(job, manifest, sb) }
        return sb.toString()
    }

    private fun renderTektonTask(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val materializedSteps = job.steps.flatMap { it.flatten() }
        sb.appendLine("    - name: ${sanitizeId(job.id)}")
        if (job.dependsOn.isNotEmpty()) sb.appendLine("      runAfter: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        job.metadata["condition"]?.let { condition ->
            val whenBlock = TargetExpressionTranslator.tektonWhen(
                condition,
                manifest.inputs,
                manifest.compatibility.expressionSupport
            ) ?: throw TargetExpressionTranslationException(
                "Target 'tekton' cannot enforce Flow condition with the supplied expression-support evidence: $condition"
            )
            sb.appendLine(whenBlock.prependIndent("      ").trimEnd())
        }
        require(materializedSteps.size == 1) {
            "Executable Tekton job '${job.id}' must resolve to exactly one structured task payload."
        }
        val step = materializedSteps.single()
        val payload = requireNotNull(step.rendererPayload) { "Executable Tekton step '${step.id}' has no renderer payload." }
        require(payload.kind == BuiltInProjectionPayloadKinds.TEKTON_TASK) {
            "Tekton cannot render payload kind '${payload.kind}' for step '${step.id}'."
        }
        sb.appendLine("      taskRef:")
        sb.appendLine("        name: ${sanitizeId(payload.reference)}")
        if (payload.parameters.isNotEmpty()) {
            sb.appendLine("      params:")
            payload.parameters.forEach { (name, value) ->
                sb.appendLine("        - name: ${sanitizeId(name)}")
                sb.appendLine("          value: ${yamlScalar(value)}")
            }
        }
    }
}

private enum class ProjectionTarget { JENKINS, GITHUB_ACTIONS, TEKTON }

private object TargetProjectionDiagnostics {
    fun append(target: ProjectionTarget, step: TargetStep, inputs: List<TargetInput>, sb: StringBuilder, indent: String, prefix: String) {
        val inputNames = inputs.map { it.name }.toSet()
        step.params.forEach { (key, value) ->
            sb.appendLine("$indent$prefix Flow param $key: ${TargetProjectionValue.render(target, value, inputNames).replace("\n", " ")}")
            opaqueNames(value).forEach { name ->
                sb.appendLine("$indent$prefix projection requirement: opaque value $name for param $key as ${TargetProjectionValue.renderOpaque(target, name)}")
                sb.appendLine("$indent$prefix runtime environment reference for param $key: \"${TargetProjectionValue.runtimeEnvName(name)}\"")
                TargetProjectionValue.mappingNote(target, name)?.let { note -> sb.appendLine("$indent$prefix $note") }
                TargetProjectionValue.structuredMappingNote(target, name)?.lines()?.forEach { line -> sb.appendLine("$indent$prefix $line") }
            }
        }
    }

    fun opaqueNames(manifest: TargetManifest): List<String> = manifest.jobs
        .flatMap { job -> job.steps.flatMap { it.flatten() } }
        .flatMap { opaqueNames(it) }
        .distinct()

    fun opaqueNames(step: TargetStep): List<String> = step.params.values.flatMap(::opaqueNames).distinct()

    private fun opaqueNames(value: String): List<String> = opaqueRefRegex.findAll(value)
        .map { it.groupValues[1] }
        .distinct()
        .toList()
}

private object TargetProjectionValue {
    fun render(target: ProjectionTarget, value: String, inputNames: Set<String>): String {
        val opaqueRendered = opaqueRefRegex.replace(value) { match -> renderOpaque(target, match.groupValues[1]) }
        return renderInputs(target, opaqueRendered, inputNames)
    }

    fun renderOpaque(target: ProjectionTarget, name: String): String = when (target) {
        ProjectionTarget.JENKINS -> "env.${safeEnvName(name)}"
        ProjectionTarget.GITHUB_ACTIONS -> githubExpression("env.${safeEnvName(name)}")
        ProjectionTarget.TEKTON -> "\$(params.${safeEnvName(name)})"
    }

    fun runtimeEnvName(name: String): String = "$" + safeEnvName(name)

    fun bindingValue(target: ProjectionTarget, name: String): String = when (target) {
        ProjectionTarget.JENKINS -> "credentials('${groovyEscape(name)}')"
        ProjectionTarget.GITHUB_ACTIONS -> githubExpression("secrets.$name")
        ProjectionTarget.TEKTON -> "flow-secrets/$name"
    }

    fun boundary(target: ProjectionTarget): String = when (target) {
        ProjectionTarget.JENKINS -> "withCredentials"
        else -> "projectionBoundary"
    }

    fun mappingSpec(target: ProjectionTarget, name: String): String = when (target) {
        ProjectionTarget.JENKINS -> "string(credentialsId: '${groovyEscape(name)}', variable: '${safeEnvName(name)}')"
        ProjectionTarget.GITHUB_ACTIONS -> safeEnvName(name)
        ProjectionTarget.TEKTON -> safeEnvName(name)
    }

    fun mappingNote(target: ProjectionTarget, name: String): String? = when (target) {
        ProjectionTarget.JENKINS -> "value mapping requirement: ${boundary(target)}([${mappingSpec(target, name)}]) exposes env.${safeEnvName(name)}"
        ProjectionTarget.GITHUB_ACTIONS -> "value mapping requirement: repository opaque value $name must be available as ${renderOpaque(target, name)}"
        ProjectionTarget.TEKTON -> "value mapping requirement: secretKeyRef name=flow-secrets key=$name"
    }

    fun structuredMappingNote(target: ProjectionTarget, name: String): String? = when (target) {
        ProjectionTarget.TEKTON -> "valueFrom:\n  secretKeyRef:\n    name: flow-secrets\n    key: $name"
        else -> null
    }

    private fun renderInputs(target: ProjectionTarget, value: String, inputNames: Set<String>): String {
        if (value in inputNames) return renderInput(target, value)
        val interpolationStart = "\${"
        val regex = Regex(Regex.escape(interpolationStart) + "([^}]+)}")
        return regex.replace(value) { match ->
            val expression = match.groupValues[1].trim()
            if (expression in inputNames) renderInputInterpolation(target, expression) else match.value
        }
    }

    private fun renderInput(target: ProjectionTarget, name: String): String = when (target) {
        ProjectionTarget.JENKINS -> "params.$name"
        ProjectionTarget.GITHUB_ACTIONS -> githubExpression("inputs.$name")
        ProjectionTarget.TEKTON -> "\$(params.$name)"
    }

    private fun renderInputInterpolation(target: ProjectionTarget, name: String): String = when (target) {
        ProjectionTarget.JENKINS -> "\${params.$name}"
        ProjectionTarget.GITHUB_ACTIONS -> githubExpression("inputs.$name")
        ProjectionTarget.TEKTON -> "\$(params.$name)"
    }
}

private val opaqueRefRegex = Regex("secret:([A-Za-z0-9_.-]+)")
private fun safeEnvName(value: String): String = "FLOW_SECRET_" + value.uppercase().replace(Regex("[^A-Z0-9_]+"), "_").trim('_').ifBlank { "OPAQUE" }
private fun yamlScalar(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""
private fun groovyString(value: String): String = "'" + value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r") + "'"
private fun groovyEscape(value: String): String = value.replace("'", "\\'")
private fun githubExpression(value: String): String = "\${{ $value }}"

private fun TargetStep.flatten(): List<TargetStep> = listOf(this) + children.flatMap { it.flatten() }
