package org.flowlang.generators.manifest

class JenkinsManifestRenderer {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "jenkins")
        val sb = StringBuilder()
        sb.appendLine("// Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("// Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        if (manifest.mappingNotes.isNotEmpty()) {
            manifest.mappingNotes.forEach { note -> sb.appendLine("// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        }
        sb.appendLine("pipeline {")
        sb.appendLine("  agent any")
        sb.appendLine("  options { timestamps() }")
        renderJenkinsParameters(manifest, sb)
        renderJenkinsEnvironment(manifest, sb)
        sb.appendLine("  stages {")
        val errorHandlerJobs = manifest.jobs.filter { it.metadata["errorHandler"] == "true" }
        val topLevelErrorHandlers = manifest.jobs.flatMap { it.steps }.filter { it.type == "error-handler" } + errorHandlerJobs.flatMap { it.steps }
        manifest.jobs.filterNot { it.metadata["errorHandler"] == "true" }.forEach { job ->
            val stageSteps = job.steps.filterNot { it.type == "error-handler" }
            if (stageSteps.isEmpty() && job.steps.isEmpty()) renderJenkinsStage(job.name, listOf("echo 'No Flow steps generated'"), sb)
            else stageSteps.forEach { renderJenkinsNode(it, manifest, sb, indent = "    ") }
        }
        sb.appendLine("  }")
        renderJenkinsPostFailure(topLevelErrorHandlers, manifest, sb)
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderJenkinsParameters(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("  parameters {")
        manifest.inputs.forEach { input ->
            when (input.type) {
                "boolean" -> sb.appendLine("    booleanParam(name: '${groovyEscape(input.name)}', defaultValue: ${input.defaultValue?.toBooleanStrictOrNull() ?: false})")
                "option" -> sb.appendLine("    choice(name: '${groovyEscape(input.name)}', choices: [${input.choices.joinToString(", ") { groovyString(it) }}])")
                else -> sb.appendLine("    string(name: '${groovyEscape(input.name)}', defaultValue: ${groovyString(input.defaultValue ?: "")})")
            }
        }
        sb.appendLine("  }")
    }

    /**
     * Binds every declared input to a FLOW_* environment variable at the pipeline level, and every
     * secret referenced by a command to a FLOW_SECRET_* variable via Jenkins `credentials()`.
     * Commands reference these through "$FLOW_NAME"/"$FLOW_SECRET_NAME", so runtime values are
     * delivered via the environment instead of being interpolated into the script body.
     */
    private fun renderJenkinsEnvironment(manifest: TargetManifest, sb: StringBuilder) {
        val secretNames = referencedSecretNames(manifest.jobs.flatMap { it.steps }.flatMap { it.collectRuns() })
        if (manifest.inputs.isEmpty() && secretNames.isEmpty()) return
        sb.appendLine("  environment {")
        manifest.inputs.forEach { input ->
            sb.appendLine("    ${flowEnvVar(input.name)} = \"\${params.${input.name}}\"")
        }
        secretNames.forEach { name ->
            sb.appendLine("    ${flowSecretEnvVar(name)} = credentials('$name')")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsNode(step: TargetStep, manifest: TargetManifest, sb: StringBuilder, indent: String) {
        when (step.type) {
            "parallel" -> {
                sb.appendLine("${indent}stage(${groovyString(step.name)}) {")
                sb.appendLine("${indent}  parallel {")
                step.children.forEach { branch ->
                    sb.appendLine("${indent}    stage(${groovyString(branch.name)}) {")
                    sb.appendLine("${indent}      steps { script {")
                    branch.children.forEach { renderJenkinsScriptLine(it, manifest, sb, "${indent}        ") }
                    sb.appendLine("${indent}      } }")
                    sb.appendLine("${indent}    }")
                }
                sb.appendLine("${indent}  }")
                sb.appendLine("${indent}}")
            }
            "condition" -> {
                val condition = step.params["condition"] ?: "true"
                sb.appendLine("${indent}stage(${groovyString(step.name)}) {")
                sb.appendLine("${indent}  when { expression { ${TargetExpressionTranslator.groovy(condition, manifest.inputs)} } }")
                sb.appendLine("${indent}  steps { script {")
                step.children.forEach { renderJenkinsScriptLine(it, manifest, sb, "${indent}    ") }
                sb.appendLine("${indent}  } }")
                sb.appendLine("${indent}}")
            }
            "approval" -> renderJenkinsStage(step.name, listOf("input message: ${groovyString(step.params["message"] ?: "Approval required")}"), sb, indent, shell = false)
            "try" -> renderJenkinsTryStage(step, manifest, sb, indent)
            "error-handler" -> Unit
            else -> renderJenkinsStage(step.name, step.toShellLines(), sb, indent)
        }
    }

    private fun renderJenkinsTryStage(step: TargetStep, manifest: TargetManifest, sb: StringBuilder, indent: String) {
        val body = step.children.firstOrNull { it.type == "try-body" }?.children.orEmpty()
        val handler = step.children.firstOrNull { it.type == "error-handler" }?.children.orEmpty()
        sb.appendLine("${indent}stage(${groovyString(step.name)}) {")
        sb.appendLine("${indent}  steps { script {")
        sb.appendLine("${indent}    try {")
        body.forEach { renderJenkinsScriptLine(it, manifest, sb, "${indent}      ") }
        sb.appendLine("${indent}    } catch (flowError) {")
        sb.appendLine("${indent}      def error = [message: flowError.getMessage()]")
        handler.forEach { renderJenkinsScriptLine(it, manifest, sb, "${indent}      ") }
        sb.appendLine("${indent}      throw flowError")
        sb.appendLine("${indent}    }")
        sb.appendLine("${indent}  } }")
        sb.appendLine("${indent}}")
    }

    private fun renderJenkinsPostFailure(handlers: List<TargetStep>, manifest: TargetManifest, sb: StringBuilder) {
        if (handlers.isEmpty()) return
        sb.appendLine("  post {")
        sb.appendLine("    failure {")
        sb.appendLine("      script {")
        sb.appendLine("        def error = [message: currentBuild.currentResult]")
        handlers.flatMap { if (it.children.isEmpty()) listOf(it) else it.children }.forEach { renderJenkinsScriptLine(it, manifest, sb, "        ") }
        sb.appendLine("      }")
        sb.appendLine("    }")
        sb.appendLine("  }")
    }

    private fun renderJenkinsScriptLine(step: TargetStep, manifest: TargetManifest, sb: StringBuilder, indent: String) {
        if (step.type == "condition") {
            val condition = step.params["condition"] ?: "true"
            sb.appendLine("${indent}if (${TargetExpressionTranslator.groovy(condition, manifest.inputs)}) {")
            step.children.forEach { renderJenkinsScriptLine(it, manifest, sb, "${indent}  ") }
            sb.appendLine("${indent}}")
            return
        }
        val condition = step.metadata["condition"]
        val lines = when {
            step.children.isNotEmpty() -> null
            step.type == "approval" -> listOf("input message: ${groovyString(step.params["message"] ?: "Approval required")}")
            step.type == "skip" -> listOf("echo ${groovyString("Flow skip: ${step.params["detail"] ?: step.name}")}")
            step.type == "fail" -> listOf("error ${groovyString(step.params["detail"] ?: step.name)}")
            else -> step.toShellLines().map { "sh(script: ${groovyScriptString(it)})" }
        }
        if (step.children.isNotEmpty()) {
            step.children.forEach { renderJenkinsScriptLine(it, manifest, sb, indent) }
            return
        }
        if (condition != null) {
            sb.appendLine("${indent}if (${TargetExpressionTranslator.groovy(condition, manifest.inputs)}) {")
            lines?.forEach { sb.appendLine("${indent}  $it") }
            sb.appendLine("${indent}}")
        } else {
            lines?.forEach { sb.appendLine("${indent}$it") }
        }
    }

    private fun renderJenkinsStage(name: String, scriptLines: List<String>, sb: StringBuilder, indent: String = "    ", shell: Boolean = true) {
        sb.appendLine("${indent}stage(${groovyString(name)}) {")
        sb.appendLine("${indent}  steps {")
        scriptLines.forEach { line ->
            if (shell) sb.appendLine("${indent}    sh(script: ${groovyScriptString(line)})") else sb.appendLine("${indent}    $line")
        }
        sb.appendLine("${indent}  }")
        sb.appendLine("${indent}}")
    }
}

class GitHubActionsManifestRenderer {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "github-actions")
        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        manifest.mappingNotes.forEach { note -> sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        sb.appendLine("name: ${yamlScalar(manifest.flowName)}")
        sb.appendLine("on:")
        sb.appendLine("  workflow_dispatch:")
        renderGithubInputs(manifest, sb)
        sb.appendLine("jobs:")
        manifest.jobs.forEach { job -> renderGitHubJob(job, manifest, sb) }
        return sb.toString()
    }

    private fun renderGithubInputs(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("    inputs:")
        manifest.inputs.forEach { input ->
            sb.appendLine("      ${sanitizeId(input.name)}:")
            sb.appendLine("        description: ${yamlScalar(input.name)}")
            sb.appendLine("        required: ${input.required}")
            val type = when (input.type) { "boolean" -> "boolean"; "option" -> "choice"; else -> "string" }
            sb.appendLine("        type: $type")
            if (input.choices.isNotEmpty()) {
                sb.appendLine("        options:")
                input.choices.forEach { sb.appendLine("          - ${yamlScalar(it)}") }
            }
            input.defaultValue?.let { sb.appendLine("        default: ${yamlScalar(it)}") }
        }
    }

    private fun renderGitHubJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        sb.appendLine("  ${sanitizeId(job.id)}:")
        sb.appendLine("    name: ${yamlScalar(job.name)}")
        sb.appendLine("    runs-on: ubuntu-latest")
        if (job.dependsOn.isNotEmpty()) sb.appendLine("    needs: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        githubJobIf(job, manifest)?.let { sb.appendLine("    if: ${githubExpression(it)}") }
        if (job.metadata["approval"] == "true") sb.appendLine("    environment: production")
        val jobRuns = job.steps.flatMap { it.collectRuns() }
        val jobInputs = referencedInputs(jobRuns, manifest.inputs)
        val jobSecrets = referencedSecretNames(jobRuns)
        if (jobInputs.isNotEmpty() || jobSecrets.isNotEmpty()) {
            sb.appendLine("    env:")
            jobInputs.forEach { input -> sb.appendLine("      ${flowEnvVar(input.name)}: ${githubExpression("inputs.${sanitizeId(input.name)}")}") }
            jobSecrets.forEach { name -> sb.appendLine("      ${flowSecretEnvVar(name)}: ${githubExpression("secrets.$name")}") }
        }
        sb.appendLine("    steps:")
        if (job.steps.isEmpty()) {
            sb.appendLine("      - name: No steps")
            sb.appendLine("        run: echo 'No Flow steps generated'")
        } else job.steps.forEach { renderGitHubStep(it, manifest, sb) }
    }

    private fun githubJobIf(job: TargetJob, manifest: TargetManifest): String? {
        val own = job.metadata["condition"]?.let { TargetExpressionTranslator.github(it, manifest.inputs) }
        if (job.metadata["errorHandler"] == "true") {
            val parts = mutableListOf("always()", "failure()")
            if (!own.isNullOrBlank()) parts += "($own)"
            return parts.joinToString(" && ")
        }
        val needs = job.dependsOn.map { dep ->
            val safeDep = sanitizeId(dep)
            val isApproval = manifest.jobs.firstOrNull { sanitizeId(it.id) == safeDep }?.metadata?.get("approval") == "true"
            if (isApproval) "(needs.$safeDep.result == 'success' || needs.$safeDep.result == 'skipped')"
            else "needs.$safeDep.result == 'success'"
        }
        val parts = mutableListOf<String>()
        if (job.dependsOn.isNotEmpty()) parts += "always()"
        if (!own.isNullOrBlank()) parts += "($own)"
        parts += needs
        return parts.takeIf { it.isNotEmpty() }?.joinToString(" && ")
    }

    private fun renderGitHubStep(step: TargetStep, manifest: TargetManifest, sb: StringBuilder) {
        if (step.module == "git" && step.action == "checkout") {
            sb.appendLine("      - name: ${yamlScalar(step.name)}")
            sb.appendLine("        uses: actions/checkout@v4")
            return
        }
        if (step.type == "approval") {
            sb.appendLine("      - name: ${yamlScalar(step.name)}")
            sb.appendLine("        run: echo ${yamlScalar("Approval gate is represented by GitHub environment protection: ${step.params["message"] ?: "Approval required"}")}")
            return
        }
        if (step.children.isNotEmpty()) {
            step.children.filterNot { it.type == "error-handler" }.forEach { renderGitHubStep(it, manifest, sb) }
            return
        }
        sb.appendLine("      - name: ${yamlScalar(step.name)}")
        step.metadata["condition"]?.let { sb.appendLine("        if: ${githubExpression(TargetExpressionTranslator.github(it, manifest.inputs))}") }
        val run = step.run?.takeIf { it.isNotBlank() } ?: "echo 'Flow: ${step.module}.${step.action} on ${step.target}'"
        sb.appendLine("        run: |")
        run.lines().forEach { sb.appendLine("          ${it.replace("\t", "  ")}") }
    }
}

class TektonManifestRenderer {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "tekton")
        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Tekton support is partial in this release; unsupported capabilities must be checked through the compatibility report.")
        manifest.mappingNotes.forEach { note -> sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}") }
        sb.appendLine("apiVersion: tekton.dev/v1")
        sb.appendLine("kind: Pipeline")
        sb.appendLine("metadata:")
        sb.appendLine("  name: ${sanitizeId(manifest.flowName)}")
        sb.appendLine("spec:")
        if (manifest.inputs.isNotEmpty()) {
            sb.appendLine("  params:")
            manifest.inputs.forEach { sb.appendLine("    - name: ${sanitizeId(it.name)}\n      type: string") }
        }
        sb.appendLine("  tasks:")
        manifest.jobs.forEach { job -> renderTektonTask(job, manifest, sb) }
        return sb.toString()
    }

    private fun renderTektonTask(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val step = job.steps.firstOrNull()
        sb.appendLine("    - name: ${sanitizeId(job.id)}")
        if (job.dependsOn.isNotEmpty()) sb.appendLine("      runAfter: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        job.metadata["condition"]?.let { condition ->
            val whenBlock = TargetExpressionTranslator.tektonWhen(condition, manifest.inputs)
            if (whenBlock != null) {
                sb.appendLine(whenBlock.prependIndent("      ").trimEnd())
            } else {
                sb.appendLine("      # Flow condition is NOT enforced here (unsupported as native Tekton when) - see [error] condition.unsupported mapping note above: $condition")
            }
        }
        sb.appendLine("      taskSpec:")
        sb.appendLine("        steps:")
        sb.appendLine("          - name: ${sanitizeId(step?.id ?: job.id)}")
        sb.appendLine("            image: alpine:3.20")
        val stepRuns = step?.collectRuns().orEmpty()
        val stepInputs = referencedInputs(stepRuns, manifest.inputs)
        val stepSecrets = referencedSecretNames(stepRuns)
        if (stepInputs.isNotEmpty() || stepSecrets.isNotEmpty()) {
            sb.appendLine("            env:")
            stepInputs.forEach { input ->
                sb.appendLine("              - name: ${flowEnvVar(input.name)}")
                sb.appendLine("                value: \"\$(params.${sanitizeId(input.name)})\"")
            }
            // Secrets are sourced from a 'flow-secrets' Kubernetes Secret (one key per secret name).
            stepSecrets.forEach { name ->
                sb.appendLine("              - name: ${flowSecretEnvVar(name)}")
                sb.appendLine("                valueFrom:")
                sb.appendLine("                  secretKeyRef:")
                sb.appendLine("                    name: flow-secrets")
                sb.appendLine("                    key: $name")
            }
        }
        sb.appendLine("            script: |")
        sb.appendLine("              #!/bin/sh")
        sb.appendLine("              set -eu")
        if (step?.type == "loop" || step?.type == "match") {
            val unit = if (step.type == "loop") "per-item iteration" else "branch selection"
            sb.appendLine("              # Flow ${step.type} body is projected inline; native $unit is NOT enforced in this partial Tekton projection (see mapping notes).")
        }
        val lines = step?.toShellLines() ?: listOf("echo 'Flow job ${job.name}'")
        lines.flatMap { it.lines() }.forEach { sb.appendLine("              ${it.replace("\t", "  ")}") }
    }
}

private fun yamlScalar(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""
private fun groovyString(value: String): String = "'" + value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r") + "'"
private fun groovyEscape(value: String): String = value.replace("'", "\\'")
private fun githubExpression(value: String): String = 36.toChar().toString() + "{{ $value }}"

private fun groovyScriptString(value: String): String = groovyString(value)

/**
 * Flattens a step (and, for container steps, its descendants) into shell command lines.
 * Loop/match bodies are recursed into rather than dropped, so partial targets still emit the
 * real body instead of silently discarding it.
 */
private fun TargetStep.toShellLines(): List<String> = when (type) {
    "action" -> listOf(run ?: "echo Flow: ${module}.${action} on ${target}")
    "retry", "match", "loop", "try-body" -> if (children.isEmpty()) listOf("echo 'Flow ${type}: ${name}'") else children.flatMap { it.toShellLines() }
    "set", "expect", "validate", "transform", "aggregate" -> listOf("echo 'Flow ${type}: ${params["detail"] ?: name}'")
    else -> listOf(run ?: "echo 'Flow ${type}: ${name}'")
}

/** All shell command strings produced anywhere in this step subtree. */
private fun TargetStep.collectRuns(): List<String> = listOfNotNull(run) + children.flatMap { it.collectRuns() }

/** The Flow inputs actually referenced (as "$FLOW_NAME") by the given command strings, in declared order. */
private fun referencedInputs(runs: List<String>, inputs: List<TargetInput>): List<TargetInput> {
    if (inputs.isEmpty()) return emptyList()
    val text = runs.joinToString("\n")
    return inputs.filter { text.contains(flowVarToken(it.name)) }
}

private val RENDERED_SECRET_TOKEN = Regex("\"\\\$FLOW_SECRET_([A-Za-z_][A-Za-z0-9_]*)\"")

/** Names of the secrets actually referenced (as "$FLOW_SECRET_NAME") by the given command strings, in first-seen order. */
private fun referencedSecretNames(runs: List<String>): List<String> {
    val text = runs.joinToString("\n")
    return RENDERED_SECRET_TOKEN.findAll(text).map { it.groupValues[1] }.distinct().toList()
}
