package org.flowlang.generators.manifest

class TektonManifestRenderer {
    fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, "tekton")
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Projection model: typed bindings; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note ->
            sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        sb.appendLine("apiVersion: tekton.dev/v1")
        sb.appendLine("kind: Pipeline")
        sb.appendLine("metadata:")
        sb.appendLine("  name: ${sanitizeId(manifest.flowName)}")
        sb.appendLine("spec:")
        if (manifest.inputs.isNotEmpty()) {
            sb.appendLine("  params:")
            manifest.inputs.forEach {
                sb.appendLine("    - name: ${sanitizeId(it.name)}\n      type: string")
            }
        }
        sb.appendLine("  tasks:")
        manifest.jobs.forEach { job -> renderTektonTask(job, manifest, sb) }
        return sb.toString()
    }

    private fun renderTektonTask(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val materializedSteps = job.steps.flatMap { it.flatten() }
        sb.appendLine("    - name: ${sanitizeId(job.id)}")
        if (job.dependsOn.isNotEmpty()) {
            sb.appendLine("      runAfter: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        }
        job.metadata["condition"]?.let { condition ->
            val whenBlock = TargetExpressionTranslator.tektonWhen(
                condition,
                manifest.inputs,
                manifest.compatibility.expressionSupport
            ) ?: throw TargetExpressionTranslationException(
                "Target 'tekton' cannot enforce Flow condition with the supplied expression-support evidence: $condition"
            )
            sb.appendLine(whenBlock.prependIndent("      ").trimEnd())
        }
        require(materializedSteps.size == 1) {
            "Executable Tekton job '${job.id}' must resolve to exactly one structured task payload."
        }
        val step = materializedSteps.single()
        val payload = requireNotNull(step.rendererPayload) {
            "Executable Tekton step '${step.id}' has no renderer payload."
        }
        require(payload.kind == BuiltInProjectionPayloadKinds.TEKTON_TASK) {
            "Tekton cannot render payload kind '${payload.kind}' for step '${step.id}'."
        }
        sb.appendLine("      taskRef:")
        sb.appendLine("        name: ${sanitizeId(payload.reference)}")
        if (payload.bindings.isNotEmpty()) {
            sb.appendLine("      params:")
            payload.bindings.forEach { (name, binding) ->
                val value = ProjectionBindingRenderer.tektonValue(binding, "${step.id}.bindings.$name")
                sb.appendLine("        - name: ${sanitizeId(name)}")
                sb.appendLine("          value: ${yamlScalar(value)}")
            }
        }
    }
}
