package org.flowlang.targets.builtin

import org.flowlang.generators.manifest.TargetEnvironmentSafetyEvidenceResolver
import org.flowlang.generators.manifest.TargetJob
import org.flowlang.generators.manifest.TargetManifest
import org.flowlang.generators.manifest.TargetManifestRenderer
import org.flowlang.generators.manifest.TargetRenderMode
import org.flowlang.generators.manifest.TargetRenderPolicy
import org.flowlang.generators.manifest.TargetRendererContractValidator
import org.flowlang.generators.manifest.TargetReviewArtifactRenderer
import org.flowlang.generators.manifest.TargetRendererPayload
import org.flowlang.generators.manifest.TargetTrigger
import org.flowlang.generators.manifest.sanitizeId
import org.flowlang.projection.ProjectionBinding

class GitHubActionsManifestRenderer(
    private val environmentEvidenceResolver: TargetEnvironmentSafetyEvidenceResolver = TargetEnvironmentSafetyEvidenceResolver()
) : TargetManifestRenderer {
    override val target: String = "github-actions"
    override val artifactFileName: String = "github-actions.yml"

    override fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, target)
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)
        requireSupportedTriggers(manifest)

        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        sb.appendLine("# Projection model: typed bindings; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note ->
            sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        sb.appendLine("name: ${yamlScalar(manifest.flowName)}")
        sb.appendLine("on:")
        val manual = manifest.triggers.isEmpty() || manifest.triggers.any { it.type == "MANUAL" }
        if (manual) {
            sb.appendLine("  workflow_dispatch:")
            renderGithubInputs(manifest, sb)
        }
        val schedules = manifest.triggers.filter { it.type == "SCHEDULE" }
        if (schedules.isNotEmpty()) {
            sb.appendLine("  schedule:")
            schedules.forEach { trigger ->
                val expression = requireNotNull(trigger.scheduleExpression) {
                    "GitHub schedule '${trigger.id}' is missing expression."
                }
                sb.appendLine("    - cron: ${yamlScalar(expression)}")
                trigger.timezone?.let { timezone ->
                    sb.appendLine("      timezone: ${yamlScalar(timezone)}")
                }
            }
        }
        renderGitHubEvents(manifest.triggers.filter { it.type == "EVENT" }, sb)
        sb.appendLine("jobs:")
        manifest.jobs.forEach { job -> renderGitHubJob(job, manifest, sb) }
        return sb.toString()
    }

    private fun requireSupportedTriggers(manifest: TargetManifest) {
        manifest.triggers.forEach { trigger ->
            require(trigger.workflows == listOf("main")) {
                "Executable GitHub trigger '${trigger.id}' must target exactly the main workflow."
            }
            require(trigger.params.isEmpty()) {
                "Executable GitHub trigger '${trigger.id}' contains unsupported untyped parameters: ${trigger.params.keys.sorted().joinToString()}."
            }
            when (trigger.type) {
                "MANUAL" -> require(trigger.scheduleKind == null && trigger.event == null) {
                    "Executable GitHub manual trigger '${trigger.id}' contains schedule or event evidence."
                }
                "SCHEDULE" -> {
                    require(trigger.scheduleKind == "CRON") {
                        "Executable GitHub schedule '${trigger.id}' must be CRON."
                    }
                    require(!trigger.scheduleExpression.isNullOrBlank()) {
                        "Executable GitHub schedule '${trigger.id}' is missing expression."
                    }
                }
                "EVENT" -> require(trigger.event in SUPPORTED_EVENTS) {
                    "Executable GitHub event '${trigger.id}' uses unsupported event identity '${trigger.event}'."
                }
                else -> error(
                    "GitHub Actions cannot render trigger '${trigger.id}' of type '${trigger.type}' without changing its semantics."
                )
            }
        }
        val eventNames = manifest.triggers.filter { it.type == "EVENT" }.mapNotNull { it.event }
        require(eventNames.size == eventNames.toSet().size) {
            "Executable GitHub manifest contains duplicate event identities: ${eventNames.groupingBy { it }.eachCount().filterValues { it > 1 }.keys.sorted().joinToString()}."
        }
    }

    private fun renderGitHubEvents(events: List<TargetTrigger>, sb: StringBuilder) {
        events.map { trigger -> requireNotNull(trigger.event) }.sorted().forEach { event ->
            sb.appendLine("  $event:")
        }
    }

    private fun renderGithubInputs(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("    inputs:")
        manifest.inputs.forEach { input ->
            sb.appendLine("      ${sanitizeId(input.name)}:")
            sb.appendLine("        description: ${yamlScalar(input.name)}")
            sb.appendLine("        required: ${input.required}")
            val type = when (input.type) {
                "boolean" -> "boolean"
                "option" -> "choice"
                else -> "string"
            }
            sb.appendLine("        type: $type")
            if (input.choices.isNotEmpty()) {
                sb.appendLine("        options:")
                input.choices.forEach { sb.appendLine("          - ${yamlScalar(it)}") }
            }
            input.defaultValue?.let { sb.appendLine("        default: ${yamlScalar(it)}") }
        }
    }

    private fun renderGitHubJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val materializedSteps = job.steps.flatMap { it.flatten() }
        val opaqueNames = materializedSteps.flatMap { TargetProjectionDiagnostics.opaqueNames(it) }.distinct()
        sb.appendLine("  ${sanitizeId(job.id)}:")
        sb.appendLine("    name: ${yamlScalar(job.name)}")
        sb.appendLine("    runs-on: ubuntu-latest")
        if (job.dependsOn.isNotEmpty()) {
            sb.appendLine("    needs: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        }
        GitHubJobConditionAuthority.expression(job, manifest)?.let {
            sb.appendLine("    if: ${githubExpression(it)}")
        }
        if (job.metadata["providerApprovalPayload"] == "true") {
            val environmentEvidence = environmentEvidenceResolver.resolve(manifest, job)
            sb.appendLine("    # Flow environment sensitivity: ${environmentEvidence.sensitivity}")
            sb.appendLine("    # Flow environment policy: ${environmentEvidence.policyPackageId}@${environmentEvidence.policyPackageVersion}")
            if (environmentEvidence.parameterEvidence.isNotEmpty()) {
                sb.appendLine("    # Flow environment evidence: ${environmentEvidence.parameterEvidence.sorted().joinToString(", ")}")
            }
            sb.appendLine("    # Flow environment decision: ${environmentEvidence.reason}")
            environmentEvidence.approvalEnvironment?.let { environment ->
                sb.appendLine("    environment: ${yamlScalar(environment)}")
            }
        }
        if (opaqueNames.isNotEmpty()) {
            sb.appendLine("    env:")
            opaqueNames.forEach { name ->
                sb.appendLine("      ${safeEnvName(name)}: ${TargetProjectionValue.bindingValue(ProjectionTarget.GITHUB_ACTIONS, name)}")
            }
        }
        require(materializedSteps.isNotEmpty()) { "Executable GitHub Actions job '${job.id}' has no steps." }
        sb.appendLine("    steps:")
        materializedSteps.forEach { step ->
            val payload = requireNotNull(step.rendererPayload) {
                "Executable GitHub Actions step '${step.id}' has no renderer payload."
            }
            require(payload.kind == BuiltInProjectionPayloadKinds.GITHUB_ACTION) {
                "GitHub Actions cannot render payload kind '${payload.kind}' for step '${step.id}'."
            }
            sb.appendLine("      - name: ${yamlScalar(step.name)}")
            sb.appendLine("        uses: ${yamlScalar(payload.reference)}")
            when (payload.reference) {
                "actions/checkout@v4" -> renderCheckoutBindings(step.id, payload, sb)
                "docker/build-push-action@v7" -> renderImageBuildBindings(step.id, payload, manifest, sb)
                else -> renderGenericBindings(step.id, payload.bindings, sb)
            }
        }
    }

    private fun renderCheckoutBindings(
        stepId: String,
        payload: TargetRendererPayload,
        sb: StringBuilder
    ) {
        val context = "GitHub checkout payload for '$stepId'"
        val repository = CheckoutProjectionValues.githubRepository(payload, "repository", context)
        val ref = CheckoutProjectionValues.branch(payload, "ref", context)
        val depth = payload.bindings["fetch-depth"]?.let {
            CheckoutProjectionValues.depth(payload, "fetch-depth", context)
        } ?: 0
        sb.appendLine("        with:")
        sb.appendLine("          repository: ${yamlScalar(repository)}")
        sb.appendLine("          ref: ${yamlScalar(ref)}")
        sb.appendLine("          fetch-depth: ${yamlScalar(depth.toString())}")
    }

    private fun renderImageBuildBindings(
        stepId: String,
        payload: TargetRendererPayload,
        manifest: TargetManifest,
        sb: StringBuilder
    ) {
        val context = "GitHub image-build payload for '$stepId'"
        val image = ImageBuildProjectionValues.renderText(
            ProjectionTarget.GITHUB_ACTIONS,
            ImageBuildProjectionValues.image(payload, "image", context),
            manifest.inputs,
            "$context binding 'image'"
        )
        val buildContext = ImageBuildProjectionValues.requireLiteralWorkspacePath(
            ImageBuildProjectionValues.buildContext(payload, "context", context),
            "$context binding 'context'"
        )
        val dockerfile = ImageBuildProjectionValues.dockerfile(payload, "dockerfile", context)?.let {
            ImageBuildProjectionValues.requireLiteralWorkspacePath(it, "$context binding 'dockerfile'")
        }
        val push = ImageBuildProjectionValues.push(payload, "push", context)

        sb.appendLine("        with:")
        ImageBuildProjectionValues.githubContext(buildContext)?.let {
            sb.appendLine("          context: ${yamlScalar(it)}")
        }
        ImageBuildProjectionValues.githubDockerfile(buildContext, dockerfile)?.let {
            sb.appendLine("          file: ${yamlScalar(it)}")
        }
        sb.appendLine("          tags: ${yamlScalar(image)}")
        sb.appendLine("          push: $push")
    }

    private fun renderGenericBindings(
        stepId: String,
        bindings: Map<String, ProjectionBinding>,
        sb: StringBuilder
    ) {
        if (bindings.isEmpty()) return
        sb.appendLine("        with:")
        bindings.forEach { (name, binding) ->
            val value = ProjectionBindingRenderer.githubValue(binding, "$stepId.bindings.$name")
            sb.appendLine("          ${sanitizeId(name)}: ${yamlScalar(value)}")
        }
    }

    private companion object {
        val SUPPORTED_EVENTS: Set<String> = setOf("push", "pull_request", "release")
    }
}
