package org.flowlang.targets.builtin

import org.flowlang.generators.manifest.TargetEnvironmentSafetyEvidenceResolver
import org.flowlang.generators.manifest.TargetJob
import org.flowlang.generators.manifest.TargetManifest
import org.flowlang.generators.manifest.TargetManifestRenderer
import org.flowlang.generators.manifest.TargetRenderMode
import org.flowlang.generators.manifest.TargetRenderPolicy
import org.flowlang.generators.manifest.TargetRendererContractValidator
import org.flowlang.generators.manifest.TargetReviewArtifactRenderer
import org.flowlang.generators.manifest.TargetRendererPayload
import org.flowlang.generators.manifest.AdapterManifestLowering.id as sanitizeId
import org.flowlang.projection.ProjectionBinding
import org.flowlang.projection.ProjectionBindingKind
import org.flowlang.projection.ProjectionBindingResolutionStatus

class GitHubActionsManifestRenderer(
    private val environmentEvidenceResolver: TargetEnvironmentSafetyEvidenceResolver = TargetEnvironmentSafetyEvidenceResolver()
) : TargetManifestRenderer {
    override val target: String = "github-actions"
    override val artifactFileName: String = "github-actions.yml"

    override fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, target)
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        sb.appendLine("# Projection model: typed bindings; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note ->
            sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        sb.appendLine("name: ${yamlScalar(manifest.flowName)}")
        sb.append(scheduleProjection(manifest))
        sb.appendLine("jobs:")
        manifest.jobs.forEach { job -> renderGitHubJob(job, manifest, sb) }
        return sb.toString()
    }

    /**
     * Retains the renderer-owned scheduling evidence boundary while delegating
     * the complete trigger mapping to the production trigger planner.
     */
    private fun scheduleProjection(manifest: TargetManifest): String =
        GitHubActionsTriggerProjectionPlanner.render(manifest)

    private fun renderGitHubJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val materializedSteps = job.steps.flatMap { it.flatten() }
        val opaqueNames = materializedSteps.flatMap { TargetProjectionDiagnostics.opaqueNames(it) }.distinct()
        sb.appendLine("  ${sanitizeId(job.id)}:")
        sb.appendLine("    name: ${yamlScalar(job.name)}")
        sb.appendLine("    runs-on: ubuntu-latest")
        if (job.dependsOn.isNotEmpty()) {
            sb.appendLine("    needs: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        }
        GitHubJobConditionAuthority.expression(job, manifest)?.let {
            sb.appendLine("    if: ${githubExpression(it)}")
        }
        if (job.metadata["providerApprovalPayload"] == "true") {
            val environmentEvidence = environmentEvidenceResolver.resolve(manifest, job)
            sb.appendLine("    # Flow environment sensitivity: ${environmentEvidence.sensitivity}")
            sb.appendLine("    # Flow environment policy: ${environmentEvidence.policyPackageId}@${environmentEvidence.policyPackageVersion}")
            if (environmentEvidence.parameterEvidence.isNotEmpty()) {
                sb.appendLine("    # Flow environment evidence: ${environmentEvidence.parameterEvidence.sorted().joinToString(", ")}")
            }
            sb.appendLine("    # Flow environment decision: ${environmentEvidence.reason}")
            environmentEvidence.approvalEnvironment?.let { environment ->
                sb.appendLine("    environment: ${yamlScalar(environment)}")
            }
        }
        if (opaqueNames.isNotEmpty()) {
            sb.appendLine("    env:")
            opaqueNames.forEach { name ->
                sb.appendLine("      ${safeEnvName(name)}: ${GitHubActionsProjectionSyntax.bindingValue(name)}")
            }
        }
        require(materializedSteps.isNotEmpty()) { "Executable GitHub Actions job '${job.id}' has no steps." }
        sb.appendLine("    steps:")
        materializedSteps.forEach { step ->
            val payload = requireNotNull(step.rendererPayload) {
                "Executable GitHub Actions step '${step.id}' has no renderer payload."
            }
            require(payload.kind == GitHubActionsProjectionPayloadKinds.GITHUB_ACTION) {
                "GitHub Actions cannot render payload kind '${payload.kind}' for step '${step.id}'."
            }
            sb.appendLine("      - name: ${yamlScalar(step.name)}")
            sb.appendLine("        uses: ${yamlScalar(payload.reference)}")
            when (payload.reference) {
                "actions/checkout@v4" -> renderCheckoutBindings(step.id, payload, sb)
                "docker/build-push-action@v7" -> renderImageBuildBindings(step.id, payload, manifest, sb)
                GitHubActionsWorkspaceContinuityPlanner.UPLOAD_REFERENCE ->
                    renderWorkspaceUploadBindings(step.id, payload, sb)
                GitHubActionsWorkspaceContinuityPlanner.DOWNLOAD_REFERENCE ->
                    renderWorkspaceDownloadBindings(step.id, payload, sb)
                else -> renderGenericBindings(step.id, payload.bindings, sb)
            }
        }
    }

    private fun renderCheckoutBindings(
        stepId: String,
        payload: TargetRendererPayload,
        sb: StringBuilder
    ) {
        val context = "GitHub checkout payload for '$stepId'"
        val repository = GitHubActionsCheckoutProjectionValues.githubRepository(payload, "repository", context)
        val ref = CheckoutProjectionValues.branch(payload, "ref", context)
        val depth = payload.bindings["fetch-depth"]?.let {
            CheckoutProjectionValues.depth(payload, "fetch-depth", context)
        } ?: 0
        sb.appendLine("        with:")
        sb.appendLine("          repository: ${yamlScalar(repository)}")
        sb.appendLine("          ref: ${yamlScalar(ref)}")
        sb.appendLine("          fetch-depth: ${yamlScalar(depth.toString())}")
    }

    private fun renderImageBuildBindings(
        stepId: String,
        payload: TargetRendererPayload,
        manifest: TargetManifest,
        sb: StringBuilder
    ) {
        val context = "GitHub image-build payload for '$stepId'"
        val image = ImageBuildProjectionValues.renderText(
            GitHubActionsProjectionSyntax,
            ImageBuildProjectionValues.image(payload, "image", context),
            manifest.inputs,
            "$context binding 'image'"
        )
        val buildContext = ImageBuildProjectionValues.requireLiteralWorkspacePath(
            ImageBuildProjectionValues.buildContext(payload, "context", context),
            "$context binding 'context'"
        )
        val dockerfile = ImageBuildProjectionValues.dockerfile(payload, "dockerfile", context)?.let {
            ImageBuildProjectionValues.requireLiteralWorkspacePath(it, "$context binding 'dockerfile'")
        }
        val push = ImageBuildProjectionValues.push(payload, "push", context)

        sb.appendLine("        with:")
        GitHubActionsImageBuildProjectionValues.githubContext(buildContext)?.let {
            sb.appendLine("          context: ${yamlScalar(it)}")
        }
        GitHubActionsImageBuildProjectionValues.githubDockerfile(buildContext, dockerfile)?.let {
            sb.appendLine("          file: ${yamlScalar(it)}")
        }
        sb.appendLine("          tags: ${yamlScalar(image)}")
        sb.appendLine("          push: $push")
    }

    private fun renderWorkspaceUploadBindings(
        stepId: String,
        payload: TargetRendererPayload,
        sb: StringBuilder
    ) {
        val context = "GitHub workspace upload payload for '$stepId'"
        val name = artifactName(payload, context)
        val path = literal(payload, "path", context)
        val ifNoFilesFound = literal(payload, "if-no-files-found", context)
        val includeHiddenFiles = literal(payload, "include-hidden-files", context)
        require(path == GitHubActionsWorkspaceContinuityPlanner.WORKSPACE_PATH) {
            "$context path '$path' does not reconstruct the declared workflow workspace."
        }
        require(ifNoFilesFound == "error") { "$context must fail when the producer workspace is empty." }
        require(includeHiddenFiles == "true") { "$context must preserve hidden workspace files." }
        sb.appendLine("        with:")
        sb.appendLine("          name: ${yamlScalar(name)}")
        sb.appendLine("          path: ${yamlScalar(path)}")
        sb.appendLine("          if-no-files-found: ${yamlScalar(ifNoFilesFound)}")
        sb.appendLine("          include-hidden-files: ${yamlScalar(includeHiddenFiles)}")
    }

    private fun renderWorkspaceDownloadBindings(
        stepId: String,
        payload: TargetRendererPayload,
        sb: StringBuilder
    ) {
        val context = "GitHub workspace download payload for '$stepId'"
        val name = artifactName(payload, context)
        val path = literal(payload, "path", context)
        require(path == GitHubActionsWorkspaceContinuityPlanner.WORKSPACE_PATH) {
            "$context path '$path' does not reconstruct the declared workflow workspace."
        }
        sb.appendLine("        with:")
        sb.appendLine("          name: ${yamlScalar(name)}")
        sb.appendLine("          path: ${yamlScalar(path)}")
    }

    private fun artifactName(payload: TargetRendererPayload, context: String): String {
        val binding = requireNotNull(payload.bindings["name"]) { "$context is missing artifact name." }
        require(binding.kind == ProjectionBindingKind.ARTIFACT) {
            "$context name must be an ARTIFACT binding, found ${binding.kind}."
        }
        require(binding.resolutionStatus == ProjectionBindingResolutionStatus.SYMBOLIC) {
            "$context artifact identity must remain symbolic."
        }
        return requireNotNull(binding.name).also {
            require(it.isNotBlank()) { "$context artifact identity must not be blank." }
        }
    }

    private fun literal(payload: TargetRendererPayload, name: String, context: String): String {
        val binding = requireNotNull(payload.bindings[name]) { "$context is missing '$name'." }
        require(binding.kind == ProjectionBindingKind.LITERAL) {
            "$context binding '$name' must be LITERAL, found ${binding.kind}."
        }
        require(binding.resolutionStatus == ProjectionBindingResolutionStatus.RESOLVED) {
            "$context binding '$name' must be resolved."
        }
        return requireNotNull(binding.value)
    }

    private fun renderGenericBindings(
        stepId: String,
        bindings: Map<String, ProjectionBinding>,
        sb: StringBuilder
    ) {
        if (bindings.isEmpty()) return
        sb.appendLine("        with:")
        bindings.forEach { (name, binding) ->
            val value = GitHubActionsProjectionBindingRenderer.githubValue(binding, "$stepId.bindings.$name")
            sb.appendLine("          ${sanitizeId(name)}: ${yamlScalar(value)}")
        }
    }
}
