package org.flowlang.targets.builtin

import org.flowlang.generators.manifest.TargetInput
import org.flowlang.generators.manifest.TargetJob
import org.flowlang.generators.manifest.TargetManifest
import org.flowlang.generators.manifest.TargetManifestRenderer
import org.flowlang.generators.manifest.TargetRenderMode
import org.flowlang.generators.manifest.TargetRenderPolicy
import org.flowlang.generators.manifest.TargetRendererContractValidator
import org.flowlang.generators.manifest.TargetRendererPayload
import org.flowlang.generators.manifest.TargetReviewArtifactRenderer
import org.flowlang.generators.manifest.TargetStep

class JenkinsManifestRenderer : TargetManifestRenderer {
    override val target: String = "jenkins"
    override val artifactFileName: String = "Jenkinsfile"

    override fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, target)
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("// Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("// Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        sb.appendLine("// Projection model: typed bindings; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note ->
            sb.appendLine("// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        sb.appendLine("pipeline {")
        sb.appendLine("  agent any")
        sb.appendLine("  options { timestamps() }")
        renderJenkinsParameters(manifest, sb)
        renderJenkinsTriggers(manifest, sb)
        renderJenkinsOpaqueEnvironment(manifest, sb)
        sb.appendLine("  stages {")
        manifest.jobs.forEach { job -> renderJenkinsJob(job, manifest, sb) }
        sb.appendLine("  }")
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderJenkinsParameters(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("  parameters {")
        manifest.inputs.forEach { input ->
            when (input.type) {
                "boolean" -> sb.appendLine("    booleanParam(name: '${groovyEscape(input.name)}', defaultValue: ${input.defaultValue?.toBooleanStrictOrNull() ?: false})")
                "option" -> sb.appendLine("    choice(name: '${groovyEscape(input.name)}', choices: [${input.choices.joinToString(", ") { groovyString(it) }}])")
                else -> sb.appendLine("    string(name: '${groovyEscape(input.name)}', defaultValue: ${groovyString(input.defaultValue ?: "")})")
            }
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsTriggers(manifest: TargetManifest, sb: StringBuilder) {
        val schedules = manifest.triggers.filter { it.type == "SCHEDULE" }
        if (schedules.isEmpty()) return
        sb.appendLine("  triggers {")
        schedules.forEach { trigger ->
            require(trigger.scheduleKind == "CRON") { "Executable Jenkins schedule '${trigger.id}' must be CRON." }
            val expression = requireNotNull(trigger.scheduleExpression) {
                "Jenkins schedule '${trigger.id}' is missing expression."
            }
            sb.appendLine("    cron(${groovyString(expression)})")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsOpaqueEnvironment(manifest: TargetManifest, sb: StringBuilder) {
        val opaqueNames = TargetProjectionDiagnostics.opaqueNames(manifest)
        if (opaqueNames.isEmpty()) return
        sb.appendLine("  environment {")
        opaqueNames.forEach { name ->
            sb.appendLine("    ${safeEnvName(name)} = credentials('${groovyEscape(name)}')")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        sb.appendLine("    stage(${groovyString(job.name)}) {")
        sb.appendLine("      steps {")
        sb.appendLine("        script {")
        if (job.steps.isEmpty()) {
            sb.appendLine("          error(${groovyString("Flow job '${job.id}' has no materialized target steps.")})")
        } else {
            job.steps.forEach { renderJenkinsStep(it, manifest, sb, "          ") }
        }
        sb.appendLine("        }")
        sb.appendLine("      }")
        sb.appendLine("    }")
    }

    private fun renderJenkinsStep(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        step.mappingNotes.forEach { note ->
            sb.appendLine("${indent}// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        TargetProjectionDiagnostics.append(ProjectionTarget.JENKINS, step, manifest.inputs, sb, indent, "//")
        when (step.type) {
            "try" -> renderJenkinsTry(step, manifest, sb, indent)
            "try-body", "error-handler", "parallel", "parallel-branch", "loop", "match", "retry" ->
                step.children.forEach { renderJenkinsStep(it, manifest, sb, indent) }
            "condition" -> renderJenkinsCondition(step, manifest, sb, indent)
            "approval" -> renderJenkinsApproval(step, sb, indent)
            else -> renderJenkinsLeaf(step, manifest, sb, indent)
        }
    }

    private fun renderJenkinsApproval(step: TargetStep, sb: StringBuilder, indent: String) {
        val payload = requireNotNull(step.rendererPayload) {
            "Executable Jenkins approval '${step.id}' has no provider renderer payload."
        }
        require(payload.kind == BuiltInProjectionPayloadKinds.JENKINS_STEP && payload.reference == "input") {
            "Jenkins approval '${step.id}' requires the owned JENKINS_STEP/input payload, not '${payload.kind}/${payload.reference}'."
        }
        val mode = requireNotNull(payload.bindings["mode"]?.value) {
            "Jenkins approval '${step.id}' is missing resolved mode binding."
        }
        require(mode == "manual") {
            "Jenkins approval '${step.id}' cannot render unsupported mode '$mode'."
        }
        val message = requireNotNull(payload.bindings["message"]?.value) {
            "Jenkins approval '${step.id}' is missing resolved message binding."
        }
        sb.appendLine("${indent}input message: ${groovyString(message)}")
    }

    private fun renderJenkinsTry(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        requireJenkinsStructure(step, "try-catch")
        val body = step.children.firstOrNull { it.type == "try-body" }
        val handler = step.children.firstOrNull { it.type == "error-handler" }
        val workflowFailure = step.metadata["workflowFailurePolicy"] == "true"
        val disposition = step.metadata["workflowFailureDisposition"]
        val errorBinding = step.metadata["workflowFailureErrorBinding"]
        if (workflowFailure) {
            require(disposition in setOf("PROPAGATE", "RECOVER")) {
                "Jenkins workflow failure boundary '${step.id}' has invalid disposition '$disposition'."
            }
            require(errorBinding != null && JENKINS_IDENTIFIER.matches(errorBinding)) {
                "Jenkins workflow failure boundary '${step.id}' has invalid error binding '$errorBinding'."
            }
        }
        sb.appendLine("${indent}try {")
        body?.children.orEmpty().forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}} catch (flowError) {")
        if (workflowFailure) {
            sb.appendLine("${indent}  def $errorBinding = flowError")
        }
        handler?.children.orEmpty().forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        if (workflowFailure && disposition == "PROPAGATE") {
            sb.appendLine("${indent}  throw flowError")
        }
        sb.appendLine("${indent}}")
    }

    private fun renderJenkinsCondition(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        requireJenkinsStructure(step, "if")
        val condition = step.params["condition"] ?: "false"
        val rendered = TargetExpressionTranslator.groovy(
            condition,
            manifest.inputs,
            manifest.compatibility.expressionSupport
        )
        sb.appendLine("${indent}if ($rendered) {")
        step.children.forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}}")
    }

    private val JENKINS_IDENTIFIER = Regex("[A-Za-z_][A-Za-z0-9_]*")

    private fun requireJenkinsStructure(step: TargetStep, reference: String) {
        val payload = requireNotNull(step.rendererPayload) {
            "Executable Jenkins structural step '${step.id}' has no provider renderer payload."
        }
        require(
            payload.kind == BuiltInProjectionPayloadKinds.JENKINS_STRUCTURE &&
                payload.reference == reference
        ) {
            "Jenkins structural step '${step.id}' requires the owned ${BuiltInProjectionPayloadKinds.JENKINS_STRUCTURE}/$reference payload, not '${payload.kind}/${payload.reference}'."
        }
    }

    private fun renderJenkinsLeaf(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        val opaqueNames = TargetProjectionDiagnostics.opaqueNames(step)
        if (opaqueNames.isNotEmpty()) {
            val items = opaqueNames.joinToString(", ") {
                TargetProjectionValue.mappingSpec(ProjectionTarget.JENKINS, it)
            }
            sb.appendLine("${indent}${TargetProjectionValue.boundary(ProjectionTarget.JENKINS)}([$items]) {")
            renderJenkinsLeafBody(step, manifest, sb, "$indent  ")
            sb.appendLine("${indent}}")
        } else {
            renderJenkinsLeafBody(step, manifest, sb, indent)
        }
    }

    private fun renderJenkinsLeafBody(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        val payload = requireNotNull(step.rendererPayload) {
            "Executable Jenkins step '${step.id}' has no renderer payload."
        }
        require(payload.kind == BuiltInProjectionPayloadKinds.JENKINS_STEP) {
            "Jenkins cannot render payload kind '${payload.kind}' for step '${step.id}'."
        }
        when (payload.reference) {
            "git" -> {
                val context = "Jenkins git payload for '${step.id}'"
                val urlBinding = requireNotNull(payload.bindings["url"]) { "$context requires url binding." }
                val branchBinding = requireNotNull(payload.bindings["branch"]) { "$context requires branch binding." }
                val urlValue = CheckoutProjectionValues.gitUrl(payload, "url", context)
                val branchValue = CheckoutProjectionValues.branch(payload, "branch", context)
                val depth = payload.bindings["depth"]?.let {
                    CheckoutProjectionValues.depth(payload, "depth", context)
                } ?: 0
                require(urlBinding.value != null && branchBinding.value != null)
                val url = groovyString(urlValue)
                val branch = groovyString(branchValue)
                if (depth == 0) {
                    sb.appendLine("${indent}git branch: $branch, url: $url")
                } else {
                    sb.appendLine("${indent}checkout scmGit(")
                    sb.appendLine("${indent}  branches: [[name: $branch]],")
                    sb.appendLine("${indent}  extensions: [cloneOption(depth: $depth, noTags: false, shallow: true)],")
                    sb.appendLine("${indent}  userRemoteConfigs: [[url: $url]]")
                    sb.appendLine("${indent})")
                }
            }
            "docker-build" -> renderDockerBuild(step.id, payload, manifest, sb, indent)
            else -> error("Unsupported Jenkins structured payload reference '${payload.reference}' for step '${step.id}'.")
        }
    }

    private fun renderDockerBuild(
        stepId: String,
        payload: TargetRendererPayload,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        val context = "Jenkins Docker build payload for '$stepId'"
        val image = ImageBuildProjectionValues.image(payload, "image", context)
        val buildContext = ImageBuildProjectionValues.requireLiteralWorkspacePath(
            ImageBuildProjectionValues.buildContext(payload, "context", context),
            "$context binding 'context'"
        )
        val dockerfile = ImageBuildProjectionValues.dockerfile(payload, "dockerfile", context)?.let {
            ImageBuildProjectionValues.requireLiteralWorkspacePath(it, "$context binding 'dockerfile'")
        }
        require(ImageBuildProjectionValues.isDefaultDockerfile(buildContext, dockerfile)) {
            "$context cannot render custom Dockerfile '$dockerfile' without falling back to Docker CLI argument strings."
        }
        val push = ImageBuildProjectionValues.push(payload, "push", context)
        val imageArgument = ImageBuildProjectionValues.jenkinsImageArgument(
            image,
            manifest.inputs,
            "$context binding 'image'"
        )
        val variable = ImageBuildProjectionValues.jenkinsVariable(stepId)
        val buildCall = if (buildContext == ".") {
            "docker.build($imageArgument)"
        } else {
            "docker.build($imageArgument, ${groovyString(buildContext)})"
        }
        sb.appendLine("${indent}def $variable = $buildCall")
        if (push) sb.appendLine("${indent}$variable.push()")
    }
}
