package org.flowlang.targets.builtin

import org.flowlang.generators.manifest.TargetInput
import org.flowlang.generators.manifest.TargetJob
import org.flowlang.generators.manifest.TargetManifest
import org.flowlang.generators.manifest.TargetManifestRenderer
import org.flowlang.generators.manifest.TargetRenderMode
import org.flowlang.generators.manifest.TargetRenderPolicy
import org.flowlang.generators.manifest.TargetRendererContractValidator
import org.flowlang.generators.manifest.TargetReviewArtifactRenderer
import org.flowlang.generators.manifest.TargetStep

class JenkinsManifestRenderer : TargetManifestRenderer {
    override val target: String = "jenkins"
    override val artifactFileName: String = "Jenkinsfile"

    override fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, target)
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("// Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("// Target: ${manifest.target}; compatibility: ${manifest.compatibility.status}")
        sb.appendLine("// Projection model: typed bindings; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note ->
            sb.appendLine("// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        sb.appendLine("pipeline {")
        sb.appendLine("  agent any")
        sb.appendLine("  options { timestamps() }")
        renderJenkinsParameters(manifest, sb)
        renderJenkinsTriggers(manifest, sb)
        renderJenkinsOpaqueEnvironment(manifest, sb)
        sb.appendLine("  stages {")
        manifest.jobs.forEach { job -> renderJenkinsJob(job, manifest, sb) }
        sb.appendLine("  }")
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderJenkinsParameters(manifest: TargetManifest, sb: StringBuilder) {
        if (manifest.inputs.isEmpty()) return
        sb.appendLine("  parameters {")
        manifest.inputs.forEach { input ->
            when (input.type) {
                "boolean" -> sb.appendLine("    booleanParam(name: '${groovyEscape(input.name)}', defaultValue: ${input.defaultValue?.toBooleanStrictOrNull() ?: false})")
                "option" -> sb.appendLine("    choice(name: '${groovyEscape(input.name)}', choices: [${input.choices.joinToString(", ") { groovyString(it) }}])")
                else -> sb.appendLine("    string(name: '${groovyEscape(input.name)}', defaultValue: ${groovyString(input.defaultValue ?: "")})")
            }
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsTriggers(manifest: TargetManifest, sb: StringBuilder) {
        val schedules = manifest.triggers.filter { it.type == "SCHEDULE" }
        if (schedules.isEmpty()) return
        sb.appendLine("  triggers {")
        schedules.forEach { trigger ->
            require(trigger.scheduleKind == "CRON") { "Executable Jenkins schedule '${trigger.id}' must be CRON." }
            val expression = requireNotNull(trigger.scheduleExpression) {
                "Jenkins schedule '${trigger.id}' is missing expression."
            }
            sb.appendLine("    cron(${groovyString(expression)})")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsOpaqueEnvironment(manifest: TargetManifest, sb: StringBuilder) {
        val opaqueNames = TargetProjectionDiagnostics.opaqueNames(manifest)
        if (opaqueNames.isEmpty()) return
        sb.appendLine("  environment {")
        opaqueNames.forEach { name ->
            sb.appendLine("    ${safeEnvName(name)} = credentials('${groovyEscape(name)}')")
        }
        sb.appendLine("  }")
    }

    private fun renderJenkinsJob(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        sb.appendLine("    stage(${groovyString(job.name)}) {")
        sb.appendLine("      steps {")
        sb.appendLine("        script {")
        if (job.steps.isEmpty()) {
            sb.appendLine("          error(${groovyString("Flow job '${job.id}' has no materialized target steps.")})")
        } else {
            job.steps.forEach { renderJenkinsStep(it, manifest, sb, "          ") }
        }
        sb.appendLine("        }")
        sb.appendLine("      }")
        sb.appendLine("    }")
    }

    private fun renderJenkinsStep(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        step.mappingNotes.forEach { note ->
            sb.appendLine("${indent}// Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        TargetProjectionDiagnostics.append(ProjectionTarget.JENKINS, step, manifest.inputs, sb, indent, "//")
        when (step.type) {
            "try" -> renderJenkinsTry(step, manifest, sb, indent)
            "try-body", "error-handler", "parallel", "parallel-branch", "loop", "match", "retry" ->
                step.children.forEach { renderJenkinsStep(it, manifest, sb, indent) }
            "condition" -> renderJenkinsCondition(step, manifest, sb, indent)
            "approval" -> sb.appendLine("${indent}input message: ${groovyString(step.params["message"] ?: "Approval required")}")
            else -> renderJenkinsLeaf(step, sb, indent)
        }
    }

    private fun renderJenkinsTry(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        val body = step.children.firstOrNull { it.type == "try-body" }
        val handler = step.children.firstOrNull { it.type == "error-handler" }
        sb.appendLine("${indent}try {")
        body?.children.orEmpty().forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}} catch (flowError) {")
        handler?.children.orEmpty().forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}}")
    }

    private fun renderJenkinsCondition(
        step: TargetStep,
        manifest: TargetManifest,
        sb: StringBuilder,
        indent: String
    ) {
        val condition = step.params["condition"] ?: "false"
        val rendered = TargetExpressionTranslator.groovy(
            condition,
            manifest.inputs,
            manifest.compatibility.expressionSupport
        )
        sb.appendLine("${indent}if ($rendered) {")
        step.children.forEach { renderJenkinsStep(it, manifest, sb, "$indent  ") }
        sb.appendLine("${indent}}")
    }

    private fun renderJenkinsLeaf(step: TargetStep, sb: StringBuilder, indent: String) {
        val opaqueNames = TargetProjectionDiagnostics.opaqueNames(step)
        if (opaqueNames.isNotEmpty()) {
            val items = opaqueNames.joinToString(", ") {
                TargetProjectionValue.mappingSpec(ProjectionTarget.JENKINS, it)
            }
            sb.appendLine("${indent}${TargetProjectionValue.boundary(ProjectionTarget.JENKINS)}([$items]) {")
            renderJenkinsLeafBody(step, sb, "$indent  ")
            sb.appendLine("${indent}}")
        } else {
            renderJenkinsLeafBody(step, sb, indent)
        }
    }

    private fun renderJenkinsLeafBody(step: TargetStep, sb: StringBuilder, indent: String) {
        val payload = requireNotNull(step.rendererPayload) {
            "Executable Jenkins step '${step.id}' has no renderer payload."
        }
        require(payload.kind == BuiltInProjectionPayloadKinds.JENKINS_STEP) {
            "Jenkins cannot render payload kind '${payload.kind}' for step '${step.id}'."
        }
        when (payload.reference) {
            "git" -> {
                val urlBinding = requireNotNull(payload.bindings["url"]) {
                    "Jenkins git payload for '${step.id}' requires url binding."
                }
                val branchBinding = payload.bindings["branch"]
                val url = ProjectionBindingRenderer.jenkinsArgument(urlBinding, "${step.id}.bindings.url")
                val branch = branchBinding?.let {
                    ProjectionBindingRenderer.jenkinsArgument(it, "${step.id}.bindings.branch")
                } ?: groovyString("main")
                sb.appendLine("${indent}git branch: $branch, url: $url")
            }
            else -> error(
                "Unsupported Jenkins structured payload reference '${payload.reference}' for step '${step.id}'."
            )
        }
    }
}
