package org.flowlang.targets.builtin

import org.flowlang.generators.manifest.TargetJob
import org.flowlang.generators.manifest.TargetManifest
import org.flowlang.generators.manifest.TargetManifestRenderer
import org.flowlang.generators.manifest.TargetRenderMode
import org.flowlang.generators.manifest.TargetRenderPolicy
import org.flowlang.generators.manifest.TargetRendererContractValidator
import org.flowlang.generators.manifest.TargetReviewArtifactRenderer
import org.flowlang.generators.manifest.TargetRendererPayload
import org.flowlang.generators.manifest.AdapterManifestLowering.id as sanitizeId

class TektonManifestRenderer : TargetManifestRenderer {
    override val target: String = "tekton"
    override val artifactFileName: String = "tekton-pipeline.yaml"

    override fun render(manifest: TargetManifest): String {
        TargetRendererContractValidator.requireRenderable(manifest, target)
        val readiness = TargetRenderPolicy.requireSafe(manifest)
        if (readiness.mode == TargetRenderMode.REVIEW_ONLY) return TargetReviewArtifactRenderer.render(manifest, readiness)
        check(readiness.mode == TargetRenderMode.EXECUTABLE)

        val sb = StringBuilder()
        sb.appendLine("# Generated by Flow standard ${manifest.standardVersion}")
        sb.appendLine("# Projection model: typed bindings; raw command execution is not emitted.")
        manifest.mappingNotes.forEach { note ->
            sb.appendLine("# Flow mapping note [${note.level}] ${note.feature} ${note.nodeId}: ${note.message.replace("\n", " ")}")
        }
        sb.appendLine("apiVersion: tekton.dev/v1")
        sb.appendLine("kind: Pipeline")
        sb.appendLine("metadata:")
        sb.appendLine("  name: ${sanitizeId(manifest.flowName)}")
        sb.appendLine("spec:")
        val projectionWorkspaces = projectionWorkspaceNames(manifest)
        if (projectionWorkspaces.isNotEmpty()) {
            sb.appendLine("  workspaces:")
            projectionWorkspaces.forEach { workspace ->
                sb.appendLine("    - name: ${sanitizeId(workspace)}")
            }
        }
        if (manifest.inputs.isNotEmpty()) {
            sb.appendLine("  params:")
            manifest.inputs.forEach {
                sb.appendLine("    - name: ${sanitizeId(it.name)}\n      type: string")
            }
        }
        sb.appendLine("  tasks:")
        manifest.jobs.forEach { job -> renderTektonTask(job, manifest, sb) }
        return sb.toString()
    }

    private fun projectionWorkspaceNames(manifest: TargetManifest): List<String> = manifest.jobs
        .flatMap { job -> job.steps.flatMap { it.flatten() } }
        .mapNotNull { step -> step.rendererPayload }
        .filter { payload -> payload.kind == TektonProjectionPayloadKinds.TEKTON_TASK }
        .mapNotNull { payload ->
            when (payload.reference) {
                "git-clone" -> CheckoutProjectionValues.workspace(payload, "workspace", "Tekton git-clone payload")
                "buildah" -> ImageBuildProjectionValues.workspace(payload, "workspace", "Tekton buildah payload")
                else -> null
            }
        }
        .distinct()

    private fun renderGitCloneTask(
        stepId: String,
        payload: TargetRendererPayload,
        sb: StringBuilder
    ) {
        val context = "Tekton git-clone payload for '$stepId'"
        val url = CheckoutProjectionValues.gitUrl(payload, "url", context)
        val revision = CheckoutProjectionValues.branch(payload, "revision", context)
        val depth = payload.bindings["depth"]?.let {
            CheckoutProjectionValues.depth(payload, "depth", context)
        } ?: 0
        val workspace = CheckoutProjectionValues.workspace(payload, "workspace", context)
        sb.appendLine("      taskRef:")
        sb.appendLine("        name: git-clone")
        sb.appendLine("      params:")
        sb.appendLine("        - name: url")
        sb.appendLine("          value: ${yamlScalar(url)}")
        sb.appendLine("        - name: revision")
        sb.appendLine("          value: ${yamlScalar(revision)}")
        sb.appendLine("        - name: depth")
        sb.appendLine("          value: ${yamlScalar(depth.toString())}")
        sb.appendLine("      workspaces:")
        sb.appendLine("        - name: output")
        sb.appendLine("          workspace: ${sanitizeId(workspace)}")
    }

    private fun renderBuildahTask(
        stepId: String,
        payload: TargetRendererPayload,
        manifest: TargetManifest,
        sb: StringBuilder
    ) {
        val context = "Tekton buildah payload for '$stepId'"
        val image = ImageBuildProjectionValues.renderText(
            TektonProjectionSyntax,
            ImageBuildProjectionValues.image(payload, "image", context),
            manifest.inputs,
            "$context binding 'image'"
        )
        val rawContext = ImageBuildProjectionValues.requireLiteralWorkspacePath(
            ImageBuildProjectionValues.buildContext(payload, "context", context),
            "$context binding 'context'"
        )
        val renderedContext = ImageBuildProjectionValues.renderText(
            TektonProjectionSyntax,
            rawContext,
            manifest.inputs,
            "$context binding 'context'"
        )
        val rawDockerfile = TektonImageBuildProjectionValues.tektonDockerfile(
            rawContext,
            ImageBuildProjectionValues.dockerfile(payload, "dockerfile", context)
        )
        ImageBuildProjectionValues.requireLiteralWorkspacePath(
            rawDockerfile,
            "$context binding 'dockerfile'"
        )
        val renderedDockerfile = ImageBuildProjectionValues.renderText(
            TektonProjectionSyntax,
            rawDockerfile,
            manifest.inputs,
            "$context binding 'dockerfile'"
        )
        val skipPush = !ImageBuildProjectionValues.push(payload, "push", context)
        val workspace = ImageBuildProjectionValues.workspace(payload, "workspace", context)

        sb.appendLine("      taskRef:")
        sb.appendLine("        name: buildah")
        sb.appendLine("      params:")
        sb.appendLine("        - name: IMAGE")
        sb.appendLine("          value: ${yamlScalar(image)}")
        sb.appendLine("        - name: CONTEXT")
        sb.appendLine("          value: ${yamlScalar(renderedContext)}")
        sb.appendLine("        - name: DOCKERFILE")
        sb.appendLine("          value: ${yamlScalar(renderedDockerfile)}")
        sb.appendLine("        - name: SKIP_PUSH")
        sb.appendLine("          value: ${yamlScalar(skipPush.toString())}")
        sb.appendLine("      workspaces:")
        sb.appendLine("        - name: source")
        sb.appendLine("          workspace: ${sanitizeId(workspace)}")
    }

    private fun renderGenericTask(
        stepId: String,
        payload: TargetRendererPayload,
        sb: StringBuilder
    ) {
        sb.appendLine("      taskRef:")
        sb.appendLine("        name: ${sanitizeId(payload.reference)}")
        if (payload.bindings.isEmpty()) return
        sb.appendLine("      params:")
        payload.bindings.forEach { (name, binding) ->
            val value = TektonProjectionBindingRenderer.tektonValue(binding, "$stepId.bindings.$name")
            sb.appendLine("        - name: ${sanitizeId(name)}")
            sb.appendLine("          value: ${yamlScalar(value)}")
        }
    }

    private fun renderTektonTask(job: TargetJob, manifest: TargetManifest, sb: StringBuilder) {
        val materializedSteps = job.steps.flatMap { it.flatten() }
        sb.appendLine("    - name: ${sanitizeId(job.id)}")
        if (job.dependsOn.isNotEmpty()) {
            sb.appendLine("      runAfter: [${job.dependsOn.joinToString(", ") { sanitizeId(it) }}]")
        }
        job.metadata["condition"]?.let { condition ->
            val whenBlock = TektonTargetExpressionTranslator.tektonWhen(
                condition,
                manifest.inputs,
                manifest.compatibility.expressionSupport
            ) ?: throw TargetExpressionTranslationException(
                "Target 'tekton' cannot enforce Flow condition with the supplied expression-support evidence: $condition"
            )
            sb.appendLine(whenBlock.prependIndent("      ").trimEnd())
        }
        require(materializedSteps.size == 1) {
            "Executable Tekton job '${job.id}' must resolve to exactly one structured task payload."
        }
        val step = materializedSteps.single()
        val payload = requireNotNull(step.rendererPayload) {
            "Executable Tekton step '${step.id}' has no renderer payload."
        }
        require(payload.kind == TektonProjectionPayloadKinds.TEKTON_TASK) {
            "Tekton cannot render payload kind '${payload.kind}' for step '${step.id}'."
        }
        when (payload.reference) {
            "git-clone" -> renderGitCloneTask(step.id, payload, sb)
            "buildah" -> renderBuildahTask(step.id, payload, manifest, sb)
            else -> renderGenericTask(step.id, payload, sb)
        }
    }
}
