# SPDX-License-Identifier: Apache-2.0
jobs:
  list_lts_releases:
    outputs: {versions: '${{ steps.lts.outputs.versions }}'}
    steps:
    - id: lts
      run: |
        versions=$(curl -sSf https://prometheus.io/download.json | jq -c '[.prometheus[] | select(.lts == true) | (.version | ltrimstr("v"))]')
        echo "versions=$versions" >> "$GITHUB_OUTPUT"
  test_version_upgrade:
    needs: list_lts_releases
    strategy:
      fail-fast: false
      matrix: {lts_version: '${{ fromJSON(needs.list_lts_releases.outputs.versions) }}'}
    steps:
    - {run: 'go test --test.lts-version=${{ matrix.lts_version }}'}
